name: Font preview

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Generate font previews
      working-directory: ./
      run: |
        # curl -L https://git.io/raw_fontpreview > fontpreview && chmod +x fontpreview
        sudo apt-get update
        sudo apt-get install xdotool sxiv fzf
        curl -L https://git.io/JfpZZ > fontpreview && chmod +x fontpreview
        ./fontpreview -i BLionTale-Regular.otf --preview-text="BONSOIR1234567890" -o preview.png
    - name: Upload preview image as artifact
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: preview.png 
        path: preview.png 
